import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { execFile } from 'child_process';
import { promisify } from 'util';
import { AuthCredentials } from '../types.js';

const execFileAsync = promisify(execFile);

const CONFIG_DIR = path.join(os.homedir(), '.config', 'resonate');
const AUTH_FILE = path.join(CONFIG_DIR, 'auth.json');
const COOKIES_FILE = path.join(CONFIG_DIR, 'cookies.txt');

export function ensureConfigDir(): void {
  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
  }
}

export function getAuthFilePath(): string {
  return AUTH_FILE;
}

export function getCookiesFilePath(): string {
  return COOKIES_FILE;
}

export function loadAuthCredentials(): AuthCredentials | null {
  try {
    if (!fs.existsSync(AUTH_FILE)) return null;
    const raw = fs.readFileSync(AUTH_FILE, 'utf-8');
    return JSON.parse(raw) as AuthCredentials;
  } catch {
    return null;
  }
}

export function saveAuthCredentials(creds: AuthCredentials): void {
  ensureConfigDir();
  fs.writeFileSync(AUTH_FILE, JSON.stringify(creds, null, 2), { mode: 0o600 });
  if (creds.cookie) {
    saveCookiesTxt(creds.cookie);
  }
}

export function clearAuthCredentials(): void {
  try {
    if (fs.existsSync(AUTH_FILE)) {
      fs.unlinkSync(AUTH_FILE);
    }
    if (fs.existsSync(COOKIES_FILE)) {
      fs.unlinkSync(COOKIES_FILE);
    }
  } catch {
    // Ignore errors during clearing
  }
}

export function saveCookiesTxt(cookieString: string): void {
  ensureConfigDir();
  // Format cookies into Netscape format for yt-dlp / curl / ffmpeg if needed
  const lines: string[] = ['# Netscape HTTP Cookie File', '# https://curl.haxx.se/docs/http-cookies.html', '# This file was generated by Resonate CLI', ''];
  const pairs = cookieString.split(';');
  for (const pair of pairs) {
    const trimmed = pair.trim();
    if (!trimmed) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const name = trimmed.substring(0, eqIdx).trim();
    const value = trimmed.substring(eqIdx + 1).trim();
    // domain, flag, path, secure, expiration, name, value
    lines.push(`.youtube.com\tTRUE\t/\tTRUE\t2147483647\t${name}\t${value}`);
  }

  fs.writeFileSync(COOKIES_FILE, lines.join('\n') + '\n', { mode: 0o600 });
}

export async function importCookiesFromBrowser(browser: string = 'chrome'): Promise<{ success: boolean; error?: string; count?: number }> {
  ensureConfigDir();
  const ytDlpPath = findExecutable('yt-dlp') || path.join(os.homedir(), '.local', 'bin', 'yt-dlp');

  try {
    const { stdout, stderr } = await execFileAsync(ytDlpPath, [
      '--cookies-from-browser',
      browser,
      '--cookies',
      COOKIES_FILE,
      '--dump-user-agent',
      'https://music.youtube.com'
    ]);

    if (fs.existsSync(COOKIES_FILE)) {
      const content = fs.readFileSync(COOKIES_FILE, 'utf-8');
      const lines = content.split('\n').filter(l => l.includes('.youtube.com') || l.includes('.google.com'));
      
      // Convert Netscape lines back to cookie header string
      const cookiePairs: string[] = [];
      for (const line of lines) {
        const parts = line.split('\t');
        if (parts.length >= 7) {
          cookiePairs.push(`${parts[5]}=${parts[6].trim()}`);
        }
      }

      const cookieHeader = cookiePairs.join('; ');
      const creds: AuthCredentials = loadAuthCredentials() || {};
      creds.cookie = cookieHeader;
      creds.lastChecked = Date.now();
      saveAuthCredentials(creds);

      return { success: true, count: cookiePairs.length };
    }

    return { success: false, error: stderr || stdout || 'No cookies extracted' };
  } catch (err: any) {
    return { success: false, error: err?.message || String(err) };
  }
}

export function findExecutable(name: string): string | null {
  const extra = [
    path.join(os.homedir(), '.local', 'bin'),
    '/opt/homebrew/bin',
    '/usr/local/bin',
    '/usr/bin',
    '/opt/local/bin',
  ];
  const envDirs = (process.env.PATH || '').split(path.delimiter).filter(Boolean);
  const dirs = [...extra, ...envDirs];
  const seen = new Set<string>();

  for (const dir of dirs) {
    if (seen.has(dir)) continue;
    seen.add(dir);
    const full = path.join(dir, name);
    try {
      const st = fs.statSync(full);
      if (!st.isFile()) continue;
      if (process.platform !== 'win32' && (st.mode & 0o111) === 0) continue;
      return full;
    } catch {
      // continue
    }
  }
  return null;
}
